### Variáveis Globais
@host = http://localhost:8080

###
# @name Listar Pacientes
GET {{host}}/pacientes
Accept: application/json

###
# @name Criar Paciente
POST {{host}}/pacientes
Content-Type: application/json

{
  "cpf": "12345678901",
  "nome": "João da Silva",
  "objetivo": "Perda de peso"
}

###
# @name Buscar Paciente por ID
# Substitua {id} por um ID válido retornado na criação ou listagem
GET {{host}}/pacientes/{id}
Accept: application/json

###
# @name Buscar Paciente por Nome
GET {{host}}/pacientes/by-name/João
Accept: application/json

###
# @name Atualizar Paciente
# Substitua {id} por um ID válido
PUT {{host}}/pacientes/{id}
Content-Type: application/json

{
  "cpf": "12345678901",
  "nome": "João da Silva Sauro",
  "objetivo": "Ganho de massa muscular"
}

###
# @name Deletar Paciente
# Substitua {id} por um ID válido
DELETE {{host}}/pacientes/{id}

###
# @name Listar Nutricionistas
GET {{host}}/nutricionistas
Accept: application/json

###
# @name Criar Nutricionista
POST {{host}}/nutricionistas
Content-Type: application/json

{
  "nome": "Dra. Maria Nutri",
  "crn": "CRN-12345"
}

###
# @name Buscar Nutricionista por ID
# Substitua {id} por um ID válido
GET {{host}}/nutricionistas/{id}
Accept: application/json

###
# @name Buscar Nutricionista por Nome
GET {{host}}/nutricionistas/by-name/Maria
Accept: application/json

###
# @name Atualizar Nutricionista
# Substitua {id} por um ID válido
PUT {{host}}/nutricionistas/{id}
Content-Type: application/json

{
  "nome": "Dra. Maria Silva Nutri",
  "crn": "CRN-54321"
}

###
# @name Deletar Nutricionista
# Substitua {id} por um ID válido
DELETE {{host}}/nutricionistas/{id}
